### ISSUE TITLE
Namespaced getAll

### ISSUE THREAD

**Issue by slaivyn** [timfpark/react-native-cache#10]
getAll is not using the namespace of the Cache instance. It is a problem for me because I am using several instances at the same time and at some point I need all the cache elements of only one instance.

I want to make a PR but I want to know if I need to preserve the current behavior with some sort of parameter like "namespaceRestriction".

**Comment by slaivyn** [comment]
I want to also namespace clearAll

**Comment by timfpark** [comment]
Fixed in 1.1.4
