### ISSUE TITLE
How can I set the time cache will expire ?

### ISSUE THREAD

**Issue by anhhtz** [timfpark/react-native-cache#11]
Hello,

How can I set the time cache will expire ?
or auto remove expired cache.

Best Regards,

**Comment by long241191** [comment]
Should auto remove expired cache for each cache key (default is global config, but we can config expired time for each cache key when put it in)

**Comment by timfpark** [comment]
This is not possible as currently implemented.  #20 however describes how this could be implemented if anyone wants to send me a PR.
