### ISSUE TITLE
Can we clear default cache from this library

### ISSUE THREAD

**Issue by sumudu-dewasurendra** [timfpark/react-native-cache#21]
Hi,
I just need to know can we clear default cache data by using
```
cache.clearAll(function(err) {
    // the whole cache is cleared now.
});
```
As an example, some of my image URLs already saved in the cache. So I need to clear those. But I'm not saving any of the data to the cache by using this library.

**Comment by timfpark** [comment]
The library will only delete the items that it knows about - it will not delete other items outside of its control.
