### ISSUE TITLE
Why cache return a weird object but not null if no this key in cache?

### ISSUE THREAD

**Issue by winglight** [timfpark/react-native-cache#27]
It's supposed to be a null or undefined when there's none cache for a certain key, but I got this:
`{"_U":0,"_V":0,"_W":null,"_X":null}`

Any hints would be appreciated!

**Comment by winglight** [comment]
I knew it. That's my fault.

**Comment by NeerajNegi** [comment]
What was the issue can you please state here? I am also facing that issue.

**Comment by winglight** [comment]
The functions of cache all are async, so "await" is necessary, otherwise, that'll return a null.
________________________________
