### ISSUE TITLE
is it possible to find cache in another page?

### ISSUE THREAD

**Issue by zakariaakli** [timfpark/react-native-cache#4]
i setted cache in a page, and want to get it from another page with getCache and the same namespace, it does'nt work, i tried aloso to pass cache object to my new page, but not working. thanks for help.

**Comment by tushgup** [comment]
Yes, I have this doubt as well. Is it possible to reference the same cache namespace from different screens?

**Comment by parth3724** [comment]
You can use it just the way you use underlying storage.
So if you use asyncstorage as storage option, YES you can use it across different screens.

**Comment by timfpark** [comment]
Exactly - yes - you can specify the same namespace from multiple locations and access the data.
