### ISSUE TITLE
Cache::getItem is defined twice

### ISSUE THREAD

**Issue by johnmarinelli** [timfpark/react-native-cache#7]
https://github.com/timfpark/react-native-cache/blob/master/lib/cache.js#L92
https://github.com/timfpark/react-native-cache/blob/master/lib/cache.js#L102

Any reason for this?

**Comment by timfpark** [comment]
Thanks for noticing that - fixed in https://github.com/timfpark/react-native-cache/commit/bb8da429c29ef0eed8dc62114a458667b3a9c480
